    - name: 'Isy99i'
      path: '~/plugins/siriproxy-isy99i'
      isyip: 'http://192.168.69.90' #IP address of the ISY-99i
      isyid: 'username'
      isypw: 'password'
      elkcode: 'code'
      camurls:	{ 'garage': 'http://192.168.69.81/cgi/jpg/image.cgi' } #URLs of IP camera image.    
      camid: 'username'
      campw: 'password'

